### ISSUE TITLE
honor information gone

### ISSUE THREAD

**Issue by dagochen** [Cjewett/HonorAssist#13]
i have no honor messages at all anymore since the merge for hooking HONOR_GAIN message

**Comment by mplachter** [comment]
@dagochen can you turn on LUA errors and post the error you receive when getting a HK please

**Comment by Cjewett** [comment]
Would also be good to know if you're using a non-English client. We have no localization right now which may be the issue.

**Comment by dagochen** [comment]
Message: Interface\AddOns\HonorAssist\HonorAssistUtils.lua:86: attempt to index local 's' (a nil value)
Time: Mon Nov 25 23:14:42 2019
Count: 2
Stack: Interface\AddOns\HonorAssist\HonorAssistUtils.lua:86: attempt to index local 's' (a nil value)
[C]: ?
Interface\AddOns\HonorAssist\HonorAssistUtils.lua:86: in function `Trim'
...erface\AddOns\HonorAssist\HonorAssistChatMessage.lua:9: in function `filterFunc'
Interface\AddOns\ElvUI\Modules\chat\Chat.lua:1166: in function `ChatFrame_MessageEventHandler'
Interface\AddOns\ElvUI\Modules\chat\Chat.lua:1553: in function `ChatFrame_OnEvent'
Interface\AddOns\ElvUI\Modules\chat\Chat.lua:1557: in function `FloatingChatFrame_OnEvent'
Interface\AddOns\ElvUI\Modules\chat\Chat.lua:1562: in function <Interface\AddOns\ElvUI\Modules\chat\Chat.lua:1561>

Locals:

**Comment by dagochen** [comment]
and Message: Interface\AddOns\HonorAssist\HonorAssistUtils.lua:86: attempt to index local 's' (a nil value)
Time: Mon Nov 25 23:14:42 2019
Count: 1
Stack: Interface\AddOns\HonorAssist\HonorAssistUtils.lua:86: attempt to index local 's' (a nil value)
[C]: ?
Interface\AddOns\HonorAssist\HonorAssistUtils.lua:86: in function `Trim'
...erface\AddOns\HonorAssist\HonorAssistChatMessage.lua:9: in function `filterFunc'
Interface\FrameXML\ChatFrame.lua:2990: in function `ChatFrame_MessageEventHandler'
Interface\AddOns\VanasKoS\modules\Synchronizer.lua:938: in function <Interface\AddOns\VanasKoS\modules\Synchronizer.lua:930>
(tail call): ?
Interface\FrameXML\ChatFrame.lua:2713: in function <Interface\FrameXML\ChatFrame.lua:2706>
(tail call): ?
(tail call): ?
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3304: in function <...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3300>

Locals:

**Comment by dagochen** [comment]
on german client

**Comment by Cjewett** [comment]
@dagochen  Thanks! Any chance you could also give us an example of what an honor gain message looks like when you kill a player? For example, in the US it's "Meelo dies, honorable kill Rank: Private (Estimated Honor Points: 54)". I want to rule out the most basic scenario since it looks like two addons could be colliding in those stack traces.

**Comment by mplachter** [comment]
@Cjewett Also the latest release will break the addon from working since we don’t have localization for the string verification of the HK

**Comment by dagochen** [comment]
You need the german message of Meelo dies, honorable kill Rank: Private (Estimated Honor Points: 54)". ?

After updating right now, i get this error:

Message: Interface\AddOns\HonorAssist\HonorAssistToolTip.lua:12: attempt to index a nil value
Time: Tue Nov 26 12:49:52 2019
Count: 6
Stack: Interface\AddOns\HonorAssist\HonorAssistToolTip.lua:12: attempt to index a nil value
[C]: ?
Interface\AddOns\HonorAssist\HonorAssistToolTip.lua:12: in function <Interface\AddOns\HonorAssist\HonorAssistToolTip.lua:7>
[C]: ?
[C]: ?
...Ons\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:95: in function <...Ons\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:87>
[C]: ?
...Ons\BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:482: in function <...Ons\BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:476>
[C]: ?
[C]: ?
...Ons\BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:408: in function <...Ons\BootyBayGazette\libs\LibExtraTip\LibExtraTip.lua:402>
[C]: in function `SetHyperlink'
Interface\AddOns\VanasKoS\modules\WarnFrame.lua:145: in function <Interface\AddOns\VanasKoS\modules\WarnFrame.lua:134>
Interface\AddOns\VanasKoS\modules\WarnFrame.lua:345: in function <Interface\AddOns\VanasKoS\modules\WarnFrame.lua:344>

Locals:

**Comment by dagochen** [comment]
German String Message: "%s stirbt. ehrenhafter Sieg, Rang: %s (Geschätzte Ehrenpunkte: %d)

**Comment by Cjewett** [comment]
@dagochen Thanks! I was watching a few streams with other languages to get an idea of what needs to happen.

1. I'll make changes so our regex is localization safe and get a patch release out. Honor gained message will still display in English.
2. Add localization across the board in 0.8 release. 

I should be able to wrap up #1 tonight and #2 in the next day.

**Comment by dagochen** [comment]
If u need help with localization...how can i help u?

**Comment by Cjewett** [comment]
@dagochen After the changes are in if you notice any translations that look incorrect it would be great if you could let us know. It won't be our native language and language translation tools aren't perfect, so the initial push probably won't be perfect. I'll try to document and make it easy to see all that is being localized.

**Comment by Cjewett** [comment]
This can be closed once https://github.com/Cjewett/HonorAssist/pull/15 is pushed to master.

**Comment by Cjewett** [comment]
@dagochen  Released a version that has language specific checks removed. 0.7.1 should fix your issue if you can confirm.

**Comment by dagochen** [comment]
seems to work for me
