### ISSUE TITLE
Dragging locked frame while outside of BG throws error

### ISSUE THREAD

**Issue by mcd8604** [Cjewett/HonorAssist#29]
Date: 2020-01-09 21:21:28
ID: 162
Error occured in: Global
Count: 2
Message: Frame HonorAssistBattlegroundFrames is not movable
Debug:
   [C]: ?
Locals:
(*temporary) = HonorAssistBattlegroundFrames {
 0 = <userdata>
 battlegroundFrame = <table> {
 }
 texture = <unnamed> {
 }
}
(*temporary) = "LeftButton"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.02.11303.01
  AtlasClassicWoW, vv1.45.01.11303.05
  AtlasLootClassic, vv1.4.4
  AtlasLootClassicData, vv1.4.4
  AtlasLootClassicDungeonsAndRaids, vv1.4.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BattlegroundTargets, v11303-4
  CharacterStatsClassic, v2.9
  ClassicAuraDurations, v
  ClassicCastbars, vv1.2.2
  ClassicCastbarsOptions, v
  CTBarMod, v8.2.5.5
  CTBottomBar, v8.2.5.7
  CTBuffMod, v8.2.5.5
  CTCore, v8.2.5.6
  CTExpenseHistory, v8.2.5.6
  CTLibrary, v8.2.5.7
  DBMCore, v1.13.28
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  GatherMate2, v1.45.5
  GuildRosterManager, v1.831
  HonorAssist, v0.9.2
  HonorTracker, vv3.2.4.1
  HPH, v2.9
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  ItemRackOptions, v
  LeatrixMaps, v1.13.42
  LeatrixPlus, v1.13.43
  NugEnergy, v1.13.12
  OmniBar, vv10.7
  OmniCC, v8.3.1
  OPie, vAncient Walnut 6
  Quartz, v3.5-classic-5
  Questie, v5.4.1
  SheepMonitor, v1.22
  Spy, v1.0.20
  SSPVP, v
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.15.5
  ZPerl, v5.8.9
  ZPerlArcaneBar, v
  ZPerlCustomHighlight, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=726)

**Comment by Cjewett** [comment]
Thanks for the report! Merged a fix into Master. Have a few other things I want to get done before releasing a new version of the addon.

**Comment by mcd8604** [comment]
tested and it works great! thank you
