### ISSUE TITLE
Add Tooltip for current Target

### ISSUE THREAD

**Issue by dagochen** [Cjewett/HonorAssist#6]
Tooltip should show the HonorAssist calculated values whenever you mouseover or target an enemy player

**Comment by mplachter** [comment]
@dagochen it should show calculated values when you mouseover an enemy. Can you explain more please?

**Comment by dagochen** [comment]
It only displays the tooltip when u mouseover. I suggest to add the tooltip also when mouseover your unitframe of your current target.

**Comment by mplachter** [comment]
Oh, Sorry for the misunderstanding. Yes we will be adding that in the next release :)

**Comment by Cjewett** [comment]
@mplachter  I think you finished this? If so we can close this out.

**Comment by mplachter** [comment]
@dagochen please update the latest release and verify the functionality
